from nimmis/java-centos:oracle-8-jdk

RUN curl -o /etc/yum.repos.d/cloudera-cdh5.repo http://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/cloudera-cdh5.repo && \
	yum install -y zookeeper -y && \
	yum install -y zookeeper-server 

